version: '3.8'
services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack:latest
    environment:
      - DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3,lambda,logs
      - LAMBDA_LIMITS_CREATE_FUNCTION_REQUEST_SIZE=100000000
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack_default
    ports:
      - "4566:4566" # Edge Port
      - "4572:4572" # S3 Port
      - "4574:4574" # Lambda Port
      - "8080:8080" # Web-UI Port
networks:
  localstack_default:
    name: localstack_default
    external: true